details:
test code:
@Test
	public void testTrustAll() throws GeneralSecurityException, IOException
{
		String fileUrl =
"https://img.ichunshen.com//54434/img/FmQcZ63oq86GAofyr-7JM4OCiHeq.jpg";
		String outputFolder = "F:\\";
		String name = Hashing.md5().hashString(fileUrl,
StandardCharsets.UTF_8) + ".jpg";

		// Open a URL Stream
		Connection connection =
Jsoup.connect(fileUrl).validateTLSCertificates(false).ignoreContentType(true);
		Response resultImageResponse = connection.execute();
		// output here
		FileOutputStream out = (new FileOutputStream(new
java.io.File(outputFolder + name)));
		out.write(resultImageResponse.bodyAsBytes()); //
resultImageResponse.body()
														// is where the image's
														// contents are.
		out.close();
	}

without modify:
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.346
sec <<< FAILURE! - in com.wen40.util.http.JsoupTest
testTrustAll()  Time elapsed: 0.346 sec  <<< FAILURE!
javax.net.ssl.SSLHandshakeException:
java.security.cert.CertificateException: Certificates does not conform
to algorithm constraints
	at com.wen40.util.http.JsoupTest.testTrustAll(JsoupTest.java:24)
Caused by: java.security.cert.CertificateException: Certificates does
not conform to algorithm constraints
	at com.wen40.util.http.JsoupTest.testTrustAll(JsoupTest.java:24)

after modify: no exception!